export const healthKeywords = [
    "health",
    "nutrition",
    "medicine",
    "mental health",
    "diet",
    "exercise",
    "fitness",
    "wellness",
    "healthy eating",
    "workout", "yoga", "meditation", "weight loss", "protein", "vitamins", "minerals", "supplements", "immune system",
    "heart health", "cardiovascular", "diabetes", "blood pressure", "cholesterol", "gut health", "probiotics", "hydration",
    "stress", "anxiety", "depression", "therapy", "counseling", "self-care", "mindfulness", "mental wellness", "brain health",
    "cognitive function", "memory", "focus", "energy", "fatigue", "chronic pain", "arthritis", "inflammation", "allergies",
    "skin care", "acne", "eczema", "oral hygiene", "vision", "eye health", "bone health", "osteoporosis", "joint health",
    "muscle recovery", "stretching", "flexibility", "strength training", "cardio", "macros", "micronutrients", "keto",
    "vegan", "vegetarian", "gluten-free", "organic", "superfoods", "antioxidants", "detox", "intermittent fasting", "meal prep",
    "healthy recipes", "smoothies", "omega-3", "fiber", "iron", "calcium", "magnesium", "zinc", "vitamin D", "vitamin C",
    "vitamin B12", "folate", "potassium", "sodium", "metabolism", "hormones", "thyroid", "autoimmune", "oncology", "anti-aging",
    "preventive care", "vaccines", "public health", "epidemiology", "infectious diseases", "COVID-19", "headache", "migraine",
    "neck pain", "posture", "physical therapy", "chiropractic", "acupuncture", "massage", "aromatherapy", "alternative medicine",
    "homeopathy", "herbal remedies", "CBD", "smoking cessation", "alcohol", "addiction", "recovery", "sobriety", "trauma",
    "PTSD", "eating disorders", "body image", "self-esteem", "happiness", "gratitude", "motivation", "goal setting", "work-life balance",
    "burnout", "remote work", "walking", "running", "cycling", "swimming", "hiking", "outdoor activities", "nature therapy", "sunlight"
];
